# Generated by Django 4.1.5 on 2023-02-17 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appsma', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Huesped',
            new_name='Clientes',
        ),
    ]
