# Generated by Django 4.1.5 on 2023-02-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appsma', '0002_rename_huesped_clientes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='telefono',
            field=models.IntegerField(blank=True),
        ),
    ]
