# Generated by Django 4.1.5 on 2023-02-24 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appsma', '0004_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avatar',
            options={},
        ),
    ]
